name: CI

permissions: read-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: "sccache"
  RISC0_BUILD_LOCKED: "1"

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup sccache
        uses: mozilla/sccache-action@v0.0.5

      - name: Check format
        run: cargo fmt -- --check

      - name: Check clippy
        run: cargo clippy --locked -- -D warnings

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup sccache
        uses: mozilla/sccache-action@v0.0.5

      - name: Build
        run: cargo build --locked

      - name: Test
        run: cargo test --locked
