name: CI

permissions: read-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  # Set RUSTC_WRAPPER to make cargo use sccache
  RUSTC_WRAPPER: "sccache"

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit-style:
    runs-on: [ self-hosted, zkrabbit-prover ]
    steps:
      - name: Checkout zkrabbit-prover
        uses: actions/checkout@v4

      # Setup sccache to cache Rust compilations
      - name: Setup sccache
        uses: mozilla/sccache-action@v0.0.5

      - name: Check format
        run: cargo fmt -- --check

      - name: Check clippy
        run: cargo clippy -- -D warnings

  build-and-test-gpu:
    runs-on: [ self-hosted, zkrabbit-prover ]
    steps:
      - name: Checkout zkrabbit-prover
        uses: actions/checkout@v4

      # Setup sccache to cache Rust compilations
      - name: Setup sccache
        uses: mozilla/sccache-action@v0.0.5

      # RISC0 SNARK conversion uses Docker internally.
      # Make sure the runner user has docker access.
      - name: Sanity check docker access
        run: |
          docker version --format 'Client={{.Client.Version}} Server={{.Server.Version}}'

      - name: Install risc0 groth16 component (for snark tests)
        run: |
          curl -L https://risczero.com/install | bash
          $HOME/.risc0/bin/rzup install risc0-groth16

      - name: Run GPU build
        run: cargo build --release --features=cuda --locked

      # Restricting tests to a single thread to avoid invalid memory errors.
      - name: Run GPU test
        run: cargo test --release --features=cuda --locked -- --nocapture --test-threads=1
